name: Ejecución cada 30 días

on:
  schedule:
    - cron: "0 0 1 */1 *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Configurar entorno de Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Instalar dependencias
      run: pip install -r requirements.txt

    - name: Ejecutar script
      run: python app.py
